name: morrisjobke.de
highlighter: rouge
permalink: /:year/:month/:day/:title/
timezone: CET
url: http://morrisjobke.de
include: [".well-known"]
markdown: kramdown
gems:
  - jekyll-seo-tag
twitter:
  username: MorrisJbk
author:
  twitter: MorrisJbk
