name: morrisjobke.de
author: Morris Jobke
pygments: true
permalink: /:year/:month/:day/:title/
timezone: CET
url: http://morrisjobke.de
include: [".well-known"]
markdown: kramdown

disqus:
    short_name: kabumgithubio
