baseURL = "https://morrisjobke.de"
disablePathToLower = true
languageCode = "en-us"
title = "Morris Jobke"
copyright = "Morris Jobke - Creative Commons Attribution 4.0 International License"
disableKinds = ["section", "taxonomy", "term"]
[social]
  twitter = "MorrisJobke"
[permalinks]
  posts = "/:year/:month/:day/:filename/"
[author]
  name = "Morris Jobke"

[mediaTypes]
[mediaTypes."application/atom"]
suffixes = ["xml"]

[outputFormats.Atom]
mediaType = "application/atom"
baseName = "feed"
isPlainText = false

[outputs]
home = [ "HTML", "Atom" ]